// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Mp6BmQ9eKYapTgVk07sEg4TK4LV4zTo',
    appId: '1:571366823050:web:6743ae63c85b999006c973',
    messagingSenderId: '571366823050',
    projectId: 'mobile-f3f40',
    authDomain: 'mobile-f3f40.firebaseapp.com',
    storageBucket: 'mobile-f3f40.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZB-YsOINfUISPzqtKJTzoLgHAk-biHRo',
    appId: '1:571366823050:android:a9e1a34575b61df406c973',
    messagingSenderId: '571366823050',
    projectId: 'mobile-f3f40',
    storageBucket: 'mobile-f3f40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIJ09Vy96SC2aJ8GOnBbuOXPd76_M7OzM',
    appId: '1:571366823050:ios:534f086151aed16e06c973',
    messagingSenderId: '571366823050',
    projectId: 'mobile-f3f40',
    storageBucket: 'mobile-f3f40.appspot.com',
    iosBundleId: 'com.example.demofb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6Mp6BmQ9eKYapTgVk07sEg4TK4LV4zTo',
    appId: '1:571366823050:web:e9bafeaf7e5c463106c973',
    messagingSenderId: '571366823050',
    projectId: 'mobile-f3f40',
    authDomain: 'mobile-f3f40.firebaseapp.com',
    storageBucket: 'mobile-f3f40.appspot.com',
  );
}
